version: '3.1'

services:

  orders_api_db:
    image: postgres
    container_name: orders_api_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=ordersapidb